{
 "title": "RED application on GO",
 "description": "Графики построенные по принципу RED.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "\"Burn rate\" Availability (POST /notes) for 5m",
   "type": "stat",
   "description": "\"Burn rate\" по Availability\nза 5 минуты. Как быстро сейчас мы рассходуем наш \"Error budget\".\n<1 - экономим\n=1 - тратим по плану\n>1 - не очень.\n>=10 поднимаем sre'шника",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((1- (sum(rate(http_requests_total{endpoint=\"/notes\",method=\"POST\",status!~\"5..\"}[5m])) / sum(rate(http_requests_total{endpoint=\"/notes\",method=\"POST\"}[5m]))) )\n/ 0.05)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI part of success POST request for 28 days",
   "type": "gauge",
   "description": "процент успешных POST запросов на создание заметки за 28 последних дней",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{endpoint=\"/notes\",method=\"POST\",status!~\"5..\"}[28d])) / sum(rate(http_requests_total{endpoint=\"/notes\",method=\"POST\"}[28d])) ) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used \"Error budget\" Availability for 28d in percent",
   "type": "stat",
   "description": "Доля использованного \"Error budget\" за 28 дней в процентах",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " ((1- (sum(rate(http_requests_total{endpoint=\"/notes\",method=\"POST\",status!~\"5..\"}[28d])) / sum(rate(http_requests_total{endpoint=\"/notes\",method=\"POST\"}[28d]))) )\n/ 0.05) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "\"Burn rate\"<5 Latency (POST /notes) for 5m",
   "type": "stat",
   "description": "\"Burn rate\" на задержку больше, чем 5 секунд. Сию-минутный вариант (5минут)",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( 1-(sum(rate(http_request_duration_seconds_bucket{endpoint=\"/notes\",method=\"POST\", le=\"5\"}[5m])) / sum(rate(http_request_duration_seconds_bucket{endpoint=\"/notes\", method=\"POST\", le=\"+Inf\"}[5m])))) / 0.0005",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI by part of latency < 5 sec  POST request",
   "type": "gauge",
   "description": "sli по части задержки меньше 5 секунды на POST заметки",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_bucket{le=\"5\",endpoint=\"/notes\",method=\"POST\"}[28d])) / sum(rate(http_request_duration_seconds_bucket{le=\"+Inf\",endpoint=\"/notes\",method=\"POST\"}[28d]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "\"Burn rate\" Latency <1 sec (POST /notes) for 5m",
   "type": "stat",
   "description": "\"Burn rate\" на задержку больше, чем 1 секунда. Сию-минутный вариант (5минут)",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1- (sum(rate(http_request_duration_seconds_bucket{le=\"1\",endpoint=\"/notes\",method=\"POST\"}[5m])) / sum(rate(http_request_duration_seconds_bucket{le=\"+Inf\",endpoint=\"/notes\",method=\"POST\"}[5m]))) ) / 0.05",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI by part of latency < 1 sec  POST request",
   "type": "gauge",
   "description": "sli по части задержки меньше 1 секунды на POST заметки",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_bucket{le=\"1\",endpoint=\"/notes\",method=\"POST\"}[28d])) / sum(rate(http_request_duration_seconds_bucket{le=\"+Inf\",endpoint=\"/notes\",method=\"POST\"}[28d]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th percentile of query times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{endpoint != \"/metrics\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (500) => 2 for last one minute",
   "type": "timeseries",
   "description": "increase()",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (method) (increase(http_errors_total{status=~\"5..\"}[1m])) >=2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Процент занятой оперативной памяти",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100, 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root File System Used",
   "type": "gauge",
   "description": "Root File System Used",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (node_filesystem_size_bytes{mountpoint=\"/\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{mountpoint=\"/\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{ mountpoint=\"/\", fstype!=\"rootfs\"}\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup checker",
   "type": "stat",
   "description": "метрика считает дату в секундах последнего бэкапа. Если время за день увеличилось, то отображается на графике 1.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(backup_success_total[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (400) => 2 for last one minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by (method) (increase(http_errors_total{status=~\"4..\"}[1m])) >=2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Only outside network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"docker0|lo\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS irate() by method",
   "type": "timeseries",
   "description": "Точная скорость запросов по методам.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by(method) (irate(http_requests_total{endpoint!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RPS sum_http_request_without_/metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{endpoint!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "{{ spide }}"
    }
   ]
  }
 ]
}